import type { Metadata } from "next";
import { Header } from "@/components/shell/Header";
import { manrope, inter, plexMono } from "@/lib/fonts";
import { ensureSession } from "@/lib/session-server";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  await ensureSession();
  return (
    <html
      lang="en"
      className={`${manrope.variable} ${inter.variable} ${plexMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
      </body>
    </html>
  );
}
